#!/bin/bash

tmpfs=${TMPFS:-/tmp}

default_mode=global
current_mode=$default_mode
mode_file=$tmpfs/qeman_mode
#mode_file=./.qeman-mode

config_fn=qeman.setups
local_config_fn=./$config_fn
xdg_config_fn=$XDG_CONFIG_HOME/qeman/$config_fn
home_config_fn=$HOME/.config/qeman/$config_fn
custom_config_fn=$QEMAN_CONFIG_FILE

# This is our config file var
# no default value
qeman_config_file=""

# Handling the mode commands
if [ "$1" == mode ]; then
	if [ "$2" == local ]; then
		echo local > $mode_file
		echo "qeman mode set to local"
	elif [ "$2" == global ]; then
		echo global > $mode_file
		echo "qeman mode set to global"
	else
		if [ -s $mode_file ]; then
			cat $mode_file
		else
			echo $default_mode > $mode_file
			cat $mode_file
		fi
	fi
	exit 0
fi

# Setting the mode on load
# Default is already set, so set only if the mode file exists
if [ -s $mode_file ]; then
	current_mode=$(cat $mode_file)
fi

# Error checking the mode file
if [ $current_mode != local -a $current_mode != global ]; then
	echo "Invalid mode"
	exit 1
fi

# Read config
if [[ -n $QEMAN_CONFIG_FILE ]]; then
	qeman_file="$QEMAN_CONFIG_FILE"
elif [[ $current_mode == local ]]; then
	qeman_file="$local_config_fn"
elif [[ $current_mode == global && -s $xdg_config_fn ]]; then
	qeman_file="$xdg_config_fn"
elif [[ $current_mode == global && -s $home_config_fn ]]; then
	qeman_file="$home_config_fn"
else
	echo "No qeman file found"
	exit 1
fi

source "${0%/*}"/bash-ini-parser

# Parse the config
if ! cfg_parser "$qeman_file" ; then
	echo "error 1"
	exit 1
fi
